apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: inventory
spec:
  schedule: '0 1 * * *'
  startingDeadlineSeconds: 200
  successfulJobsHistoryLimit: 1
  suspend: false
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - command:
            - /bin/bash
            args:
            - "/lbn/inventory.sh"
            env:
              - name: AWS_ACCESS_KEY_ID 
                valueFrom:
                  secretKeyRef:
                    name: aws
                    key: access_key_id
              - name: AWS_SECRET_ACCESS_KEY 
                valueFrom:
                  secretKeyRef:
                    name: aws
                    key: secret_access_key
            envFrom:
            - configMapRef:
                name: envars
            image: {{ .Values.inventory.image }}:{{ .Values.inventory.tag}}
            imagePullPolicy: Always
            name: inventory
            resources: {}
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
          dnsPolicy: ClusterFirst
          restartPolicy: Never
          schedulerName: default-scheduler
          securityContext: {}
          terminationGracePeriodSeconds: 30
