name: Helm Publish
on:
  push:
    tags:
    - v*
jobs:
  build:
    name: Deployment
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Helm Chart Releaser
      uses: helm/chart-releaser-action@v1.2.1
      with:
        # The chart-releaser version to use (default: v1.2.1)
        version: # optional
        # The relative path to the chart-releaser config file
        config: # optional
        # The charts directory
        charts_dir: # optional, default is charts
        # The GitHub Pages URL to the charts repo (default: https://<owner>.github.io/<repo>)
        charts_repo_url: https://github.com/linkbynet/kubernetes-repo-helm
